---
sudo: false
dist: trusty
language: generic

services:
  - docker

env:
  global:
    - TOOLS_DIR=${HOME}/bin
    - PATH="${TOOLS_DIR}:${PATH}"

    # Service Information
    - SERVICE_NAME=qotm

    # Kubectl Configuration
    - KUBECTL_VERSION=1.6.6
    - KUBECTL_SHA256SUM=c7e1830010f58ca42e4b201ea712683d1f52f4c43b2af28cbe216257da963645

    # GitHub Configuration
    - GH_USERNAME="d6e-automaton"
    - GH_USER_EMAIL="dev@datawire.io"
    - GH_REPO="${TRAVIS_REPO_SLUG}"

    # Docker Configuration
    - DOCKER_IMAGE=datawire/${SERVICE_NAME}:${TRAVIS_COMMIT}

    # Kubernetes Configuration
    - NAMESPACE=datawire

    # Secure Credentials
    #
    # - GH_TOKEN
    #
    - secure: "nVdndthl4J+kobY6L+KepewsRo+yR2xmU3DKipz1oPBu34Q7w0hKyMeXHrbuxj6gKKVjlGyPYnvL9xuxgWj9rezNguLpi0QOeL3d25jKBjtZjiIk4Gr8wgIckh6Yy71KRfVxWayW4LRLIBtZfOsZLMNCZtDXLOQWXU9a5/zhmr06RLFBkqyqOodKD69W8acXc1Uhh0+uBwgkX8fn8GRxUdnknUmVzCBx0DNEW+zy4rcb+cX+2Ep7COkmRF2JWOK9z80INkoPbdfN3db355iO2GOk1C8Bp3svJz7p/dkGoIhoOjHntbCmxKzEyyQYeeo3/lvCE5vEHnTehmd6ogAEg6j8wOPIeDUqGAMDymlf1aSMxKL2DmZO1xFyo7AxShjIEprkLPLyzA2ZjDYG06ZkZoO6kQRgHHisIZEBelydrVQnZKHk5w/kLBsF/K3KG6SAoLaqU/g7CsFjEz5wxq5vjDwKSVmUCAq3zC5d9aYijHO20jdZt2WCQPZbSqr2IJNgSwnwCZ43vQRMO1Ur7E6weEet5ldOiDBUFhdxBI7UW9Q/Qo19BDlmUwf90ACPH4/TD/WteoDeZkH1o6n1OcfPmaOKFWbq+ZAxaddyeFCE5eE2kSllCrb4bwyB5j9LD5vvEt2gg1M5l52f+DNM7Vw2hOkGFEIagCW8Ry39494HMCg="

cache:
  pip: true
  directories:
    - "${HOME}/bin"

before_install:
  - bash travis/setup_travis.sh
  - kubectl cluster-info

install:
  - set -e
  - bash travis/install_kubectl.sh

script:
  - set -e
  - bash travis/configure_git.sh
  - bash travis/build_docker_image.sh
  - bash travis/deploy_ephemeral.sh

#after_success:
#  - bash travis/push_docker_image.sh

#after_success:
##  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash bin/generate_terraform_plan.sh; fi
##  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then python3 bin/comment_pull_request.py; fi
#
#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: travis/deploy.sh prod
#    on:
#      branch: master