---
sudo: false
dist: trusty
language: generic

services:
  - docker

env:
  global:
    - TOOLS_DIR=${HOME}/bin
    - PATH="${TOOLS_DIR}:${PATH}"

    - COMMIT_HASH=${TRAVIS_COMMIT::8}

    # Service Information
    - SERVICE_NAME=qotm

    # Kubectl Configuration
    - KUBECTL_VERSION=1.6.6
    - KUBECTL_SHA256SUM=c7e1830010f58ca42e4b201ea712683d1f52f4c43b2af28cbe216257da963645

    # GitHub Configuration
    - GH_USERNAME="d6e-automaton"
    - GH_USER_EMAIL="dev@datawire.io"
    - GH_REPO="${TRAVIS_REPO_SLUG}"

    # Docker Configuration
    - DOCKER_IMAGE=datawire/${SERVICE_NAME}:${COMMIT_HASH}

    # Kubernetes Configuration
    - NAMESPACE=datawire

    # Secure Credentials
    #
    # - DOCKER_USERNAME
    # - DOCKER_PASSWORD
    # - GH_TOKEN
    #
    - secure: "d0VSgIkdg+zJhEZFWd3MvHHFwZF424paQ/X5B82VjUsc/iSEFtx1ErVdFyyfYUE98kU+tMfUyQ3qjwIRIS/pehiEIVCy7BX/V/JBn/7tr+43YCMtflhZ75v3Lq54cedb9SRIDu75RuqNOoEPLtFmOfcah3g0upju6er4p/0C7tqU/a8j+vzgabhxQ55zKcF+hQa8DnqM2qavHHJjKcp0iu2bxAP80b2LVMfRRw5PaEh295B9PloVY02Mba5xr6MJxrd9Hxa2YJCkRbXoVLG9KLofgbSbAR5130JZQn6p5wXjlGosSzEwwRvQU3DYSJuVW6mbzm/K6ZrFe2xj80kXSgt9OOqSO2vwyMIwOfJB6ElCjmovJUIKgBe4ba619zDcoLTJdetQGB9XybYqlSAkkDqdoSNlXC7VG1bToog3vfIO0zkmSl9E8Eur0zJ/RrFAq/N9j7T4v2QM7DJP/HlqspUuWiY6RL+Zx8LT4g9YP0+1tGslh/KkjTXWuxUshAAd29DXMqU1cZh7DRpzQr9jIhCl7vAWRTkOLF6eYs50PYsyMBhFOHQza93WZAPjmFFP7Ka9ZW2VSEKQTSzXx69SGmx1CmBJEqISFQ/igIlcGDAYKaGzN7hRBavf3PTJ4Uuhyp/DgTbOLaxbsmziTgXTVxCd+T+wzs9ekt39mjwfxD4="

cache:
  pip: true
  directories:
    - "${HOME}/bin"

before_install:
  - bash travis/setup_travis.sh
  - kubectl cluster-info

install:
  - set -e
  - bash travis/install_kubectl.sh

script:
  - set -e
  - bash travis/configure_git.sh
  - bash travis/build_docker_image.sh
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - bash travis/push_docker_image.sh
  - bash travis/deploy_ephemeral.sh
  - sleep 30s
  - bash travis/port_forward.sh
  - bash travis/simulate_remote_tests.sh
  - bash cleanup_ephemeral.sh

after_success:
  - bash cleanup_ephemeral.sh

before_deploy:
  - bash create_manifests.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: travis/deploy.sh
    on:
      branch: master
