---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qotm
  namespace: __namespace__
spec:
  replicas: 2
  strategy:
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: qotm
    spec:
      containers:
      - name: qotm
        image: __container_image_name__
        ports:
        - name: http-api 
          containerPort: 5000
